org: emblut
service: shui-exam

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::369812826431:role/API-DB-Lambda
  httpApi:
    cors: true

functions:
  createMessage:
    handler: functions/createMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: post

  getMessages:
    handler: functions/getMessages/index.handler
    events:
      - httpApi:
          path: /messages
          method: get

  updateMessage:
    handler: functions/updateMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: put

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MessagesTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: IdIndex
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - id
          - IndexName: UsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
              - AttributeName: sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
